### ISSUE TITLE
Using Edge - Chakra in WIndows 10

### ISSUE THREAD

**Issue by mikeptweet** [Lexikos/ActiveScript.ahk#1]
Hi Lexikos ... This is an awesome script. Thank you very much for sharing. I was wondering if it could be modified to include the new Chakra.dll from Windows 10, as per this article and code sample - http://www.panopticoncentral.net/2015/09/09/the-two-faces-of-jsrt-in-windows-10/

Unfortunately, I don't have the skills to make this happen.

I would be willing to offer some form of compensation to make this happen.

cheers,
mike

**Comment by Lexikos** [comment]
JsRT is somewhat simpler to utilize than IActiveScript. ActiveScript.ahk is based entirely around the IActiveScript interface, so is mostly not applicable to JsRT. I've added a new library in commit f03bc0b4 for hosting the new JavaScript engine: JsRT.ahk.

The differences between the IE11 version of JsRT and the Edge version are minimal; JsRT.ahk supports both as documented in the readme.

**Comment by mikeptweet** [comment]
This is awesome ... thank you so much for your quick response! Do you have a https://www.paypal.me/ account? I'd like to give a small donation for your efforts.
