### ISSUE TITLE
using Node-chakracore as the scripting engine?

### ISSUE THREAD

**Issue by mikeptweet** [Lexikos/ActiveScript.ahk#3]
I love this library ... thanks so much for sharing it.

I was wondering how much work would be involved in adding Node-chakracore as a scripting engine to your library? Is this possible?

https://github.com/nodejs/node-chakracore

**Comment by Lexikos** [comment]
A brief look indicates that node-chakracore is an application (node.exe) which embeds the ChakraCore engine. It is not a library. So no, it is not possible.

Furthermore, ChakraCore and Chakra aren't the same thing.  I think ChakraCore omits the COM-interop functions, which are a fundamental requirement for JsRT.ahk.
