### ISSUE TITLE
Script crash when loading jsRT with page with js error.

### ISSUE THREAD

**Issue by RaptorX** [Lexikos/ActiveScript.ahk#5]
using Beta.3 with the following code:

```
#Include <ActiveScript.ahk\JsRT>
; js := (JsRT.Edge)()

f1::
linkLaws(*)
{
	tempGui := Gui()
	wb := tempGui.AddActiveX("w300 h300", "Shell.Explorer").Value
	wb.Navigate("https://dejure.org/gesetze/StGB/244#Abs2")
	tempGui.Show()
}
```

when loading i get the following error:
![image](https://user-images.githubusercontent.com/328761/174823643-be9d612a-e2aa-4544-bb69-2e85e001b6f1.png)

**As soon as I uncomment line 2, to load a JsRT.Edge object if I run the script, what happens is a silent crash.**
The interesting part is that the js object is not used on the code above. So I was not sure if they were related, but commenting the line fixes the issue.

**Comment by RaptorX** [comment]
Changing line 2 to `js := (JsRT.IE)()` seems to fix the issue.

**Comment by Lexikos** [comment]
It is a "formerly documented" limitation of the IE11 and Edge JavaScript runtimes.

Microsoft appears to have lost the documentation for JsRT, but the relevant part is [archived](https://web.archive.org/web/20160813164657/https://msdn.microsoft.com/en-us/library/dn903710%28v=vs.94%29.aspx):

> Your app can support only one version of JsRT per process.
>
> For example, you can’t create an Edge engine runtime and then a legacy engine runtime and expect them to run correctly in the same process. This is unsupported and may result in undocumented behavior, such as failure to load the second DLL.

ChakraCore would probably work, but it isn't identical to JsRT and doesn't support IDispatch (or didn't last time I checked).

You're probably better off replacing IE11 with WebView2.
